# Generated by Django 4.2.5 on 2023-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
